name: Verify

on:
  push:
    branches-ignore:
      - main  # Trigger on every push to any branch ingnore main

jobs:
  build:
    name: 🔨 Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace
